# Etapa 1: Construcción del binario
FROM golang:1.23-alpine AS build

# Crear directorio de trabajo
WORKDIR /app

# Copiar el archivo go.mod y go.sum
COPY go.mod go.sum ./

# Descargar las dependencias
RUN go mod download

# Copiar todo el código de la aplicación
COPY . .

# Compilar la aplicación
RUN go build -o app .

# Etapa 2: Imagen ligera para ejecutar el binario
FROM alpine:latest

# Crear un directorio de trabajo
WORKDIR /root/

# Copiar el binario desde la etapa de construcción
COPY --from=build /app/app .

# Exponer el puerto en el que la aplicación escucha
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./app"]
